### ISSUE TITLE
M1: Design modules database 

### ISSUE THREAD

**Issue by omartounsi7** [omartounsi7/ECE461_Part2#4]
Database will contain all relevant data pertaining to the modules and will contain the path to where the module is stored in the cloud storage.

**Comment by kevintl1998** [comment]
The modules database must be remade in GCP before proper testing and submission. The current modules database is set up as a sandbox database, which is not sufficient for our product when it goes into production.

**Comment by omartounsi7** [comment]
Database was set up on GCP and the code accessing it was merged with the server-api-endpoints PR. Closing.
