### ISSUE TITLE
M1: Design username-password database 

### ISSUE THREAD

**Issue by omartounsi7** [omartounsi7/ECE461_Part2#5]
Database will contain the username, password, permissions, and other relevant information about each user.

**Comment by kevintl1998** [comment]
The user-info database must be remade in GCP before proper testing and submission. The current user-info database is set up as a sandbox database, which is not sufficient for our product when it goes into production.

**Comment by omartounsi7** [comment]
Database was set up on GCP and the code accessing it was merged with the server-api-endpoints PR. Closing.
